// TESTING/components/sidebar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { Edit, BookOpen, Layers } from "lucide-react"

interface SidebarProps {
  isOpen: boolean
  onClose: () => void
}

export default function Sidebar({ isOpen, onClose }: SidebarProps) {
  const pathname = usePathname()

  const navItems = [
    {
      name: "Create",
      href: "/create",
      icon: <Edit className="w-6 h-6 mr-2" />,
    },
    {
      name: "Categories",
      href: "/categories",
      icon: <Layers className="w-6 h-6 mr-2" />,
    },
    {
      name: "My Books",
      href: "/my-books",
      icon: <BookOpen className="w-6 h-6 mr-2" />,
    },
  ]

  return (
    <div className={`fixed inset-0 z-50 ${isOpen ? "block" : "hidden"}`} onClick={onClose}>
      <div className="fixed left-0 top-0 bottom-0 w-64 bg-medium-blue p-4 z-50" onClick={(e) => e.stopPropagation()}>
        <nav className="flex flex-col space-y-4 mt-16">
          {navItems.map((item) => (
            <Link
              key={item.name}
              href={item.href}
              className={`flex items-center p-4 rounded-md text-white ${
                pathname === item.href ? "bg-dark-blue" : "hover:bg-dark-blue transition-colors"
              }`}
            >
              {item.icon}
              {item.name}
            </Link>
          ))}
        </nav>
      </div>
    </div>
  )
}

// frontend/PassionLecture/src/components/Sidebar.vue
<template>
  <div class="sidebar-overlay" :class="{ hidden: !isOpen }" @click="onClose">
    <div class="sidebar" @click.stop>
      <nav class="nav-container">
        <router-link
          v-for="item in navItems"
          :key="item.name"
          :to="item.href"
          class="nav-item"
          :class="{ active: $route.path === item.href }"
        >
          <!-- Use component when available, otherwise fallback to image -->
          <img v-if="!areIconsAvailable" :src="item.iconImage" class="nav-icon" alt="icon" />
          <component v-else :is="item.icon" class="nav-icon" />
          {{ item.name }}
        </router-link>
      </nav>
    </div>
  </div>
</template>

<script>
import { defineComponent, ref } from 'vue'
import { useRoute } from 'vue-router'

// TODO: Uncomment when lucide-vue-next is installed
// import { Edit, BookOpen, Layers } from 'lucide-vue-next'

export default defineComponent({
  name: 'Sidebar',
  components: {
    // Will be available when uncommented above
    // Edit,
    // BookOpen,
    // Layers,
  },
  props: {
    isOpen: {
      type: Boolean,
      required: true,
    },
    onClose: {
      type: Function,
      required: true,
    },
  },
  setup() {
    const route = useRoute()
    const areIconsAvailable = ref(false) // Set to true when icons are available

    // Use these mock objects until real components are available
    const mockIcons = {
      Edit: 'Edit',
      Layers: 'Layers',
      BookOpen: 'BookOpen',
    }

    const navItems = [
      {
        name: 'Create',
        href: '/create',
        icon: mockIcons.Edit,
        iconImage: '../../public/images/Group 45.png',
      },
      {
        name: 'Categories',
        href: '/categories',
        icon: mockIcons.Layers,
        iconImage: '../../public/images/Group 44.png',
      },
      {
        name: 'My Books',
        href: '/my-books',
        icon: mockIcons.BookOpen,
        iconImage: '../../public/images/Group 54.png',
      },
    ]

    return {
      navItems,
      areIconsAvailable,
    }
  },
})
</script>

<style scoped>
.sidebar-overlay {
  position: fixed;
  inset: 0;
  z-index: 50;
}

.hidden {
  display: none;
}

.sidebar {
  position: fixed;
  left: 0;
  top: 0;
  bottom: 0;
  width: 16rem;
  background-color: var(--medium-blue, #3c5a78);
  padding: 1rem;
  z-index: 50;
}

.nav-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin-top: 4rem;
}

.nav-item {
  display: flex;
  align-items: center;
  padding: 1rem;
  border-radius: 0.375rem;
  color: white;
  text-decoration: none;
}

.nav-item:not(.active):hover {
  background-color: var(--dark-blue, #1a3c5a);
  transition: background-color 0.3s;
}

.nav-item.active {
  background-color: var(--dark-blue, #1a3c5a);
}

.nav-icon {
  width: 1.5rem;
  height: 1.5rem;
  margin-right: 0.5rem;
}

.nav-icon {
  width: 1.5rem;
  height: 1.5rem;
  margin-right: 0.5rem;
}
</style>
