// frontend/PassionLecture/src/components/Footer.vue
<template>
  <footer class="bg-green-200 text-white py-10 text-center">
    <div
      class="max-w-6xl mx-auto px-4 flex flex-col md:flex-row justify-between items-start md:items-center"
    >
      <div class="mb-6 md:mb-0 text-left">
        <h2 class="text-xl font-bold mb-2">Créateurs d’application:</h2>
        <p>Yosef N.</p>
        <p>Antoine P.</p>
        <p>Charles-Henri M.</p>
      </div>
      <div class="text-left">
        <h2 class="text-xl font-bold mb-2">Contacts:</h2>
        <p>pn25kdv@eduvaud.ch</p>
        <p>pn01kbc@eduvaud.ch</p>
        <p>pc01zcg@eduvaud.ch</p>
      </div>
    </div>
    <h1 class="text-3xl font-extrabold mt-8">Passion Lecture</h1>
  </footer>
</template>

<script></script>

<style scoped>
footer {
  width: 100%;
  background-color: #b6e1c6; /* Match the green shade */
}
</style>

// TESTING/components/footer.tsx
export default function Footer() {
  return (
    <footer className="bg-primary-green py-6 px-4 text-center">
      <h2 className="text-3xl font-bold mb-6">Passion Lecture</h2>

      <div className="flex flex-col md:flex-row justify-center gap-8 md:gap-16">
        <div>
          <h3 className="font-semibold mb-2">App Creators:</h3>
          <p>Yosef N.</p>
          <p>Antoine P.</p>
          <p>Charles-Henri M.</p>
        </div>

        <div>
          <h3 className="font-semibold mb-2">Contacts:</h3>
          <p>pn25kdv@eduvaud.ch</p>
          <p>pn01kbc@eduvaud.ch</p>
          <p>pc01zcg@eduvaud.ch</p>
        </div>
      </div>
    </footer>
  )
}
